'use client'

import { useMemo, useState, useEffect, useCallback } from 'react'
import { usePredictions } from '@/hooks/usePredictions'
import { useStockPrices } from '@/hooks/useStockPrices'
import { PredictionCard } from './PredictionCard'
import { AccuracyMetrics } from './AccuracyMetrics'
import { Skeleton } from '@/components/ui/skeleton'
import { cn } from '@/lib/utils'
import { PlayCircle, Loader2, CheckCircle2 } from 'lucide-react'
import { isCheckpointReady } from '@/utils/checkpointCalculations'
import type { CheckpointEvaluation } from '@/types/database'

type Props = {
  ticker?: string
}

type CheckpointSummary = {
  ready5d: number
  ready10d: number
  ready20d: number
  totalReady: number
}

function calculateCheckpointSummary(
  predictions: { predicted_at: string; evaluation_5d: CheckpointEvaluation | null; evaluation_10d: CheckpointEvaluation | null; evaluation_20d: CheckpointEvaluation | null }[]
): CheckpointSummary {
  let ready5d = 0, ready10d = 0, ready20d = 0

  // Use shared utility for consistent "ready" determination
  predictions.forEach(p => {
    if (isCheckpointReady(p.predicted_at, '5d', !!p.evaluation_5d)) ready5d++
    if (isCheckpointReady(p.predicted_at, '10d', !!p.evaluation_10d)) ready10d++
    if (isCheckpointReady(p.predicted_at, '20d', !!p.evaluation_20d)) ready20d++
  })

  return { ready5d, ready10d, ready20d, totalReady: ready5d + ready10d + ready20d }
}

export function PredictionHistory({ ticker }: Props) {
  const { predictions, loading, error, refetch } = usePredictions(ticker)
  const [autoEvaluating, setAutoEvaluating] = useState(false)
  const [autoEvaluationRan, setAutoEvaluationRan] = useState(false)
  const [bulkEvaluating, setBulkEvaluating] = useState(false)
  const [evaluationMessage, setEvaluationMessage] = useState<string | null>(null)
  
  const symbols = useMemo(() => {
    const uniqueTickers = new Set<string>()
    predictions.forEach(p => {
      if (p.stock?.ticker) uniqueTickers.add(p.stock.ticker)
    })
    return Array.from(uniqueTickers)
  }, [predictions])
  
  const { prices } = useStockPrices(symbols)

  const checkpointSummary = useMemo<CheckpointSummary>(
    () => calculateCheckpointSummary(predictions),
    [predictions]
  )

  const runAutoEvaluation = useCallback(async () => {
    if (autoEvaluationRan || autoEvaluating) return
    if (checkpointSummary.totalReady === 0) return
    
    setAutoEvaluating(true)
    try {
      const response = await fetch('/api/evaluate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ autoEvaluate: true })
      })
      const responseData = await response.json()
      if (responseData.summary?.evaluated > 0) {
        setEvaluationMessage(`Auto-evaluated ${responseData.summary.evaluated} checkpoint(s)`)
        refetch()
      }
    } catch (err) {
      console.error('Auto-evaluation failed:', err)
    } finally {
      setAutoEvaluating(false)
      setAutoEvaluationRan(true)
    }
  }, [autoEvaluationRan, autoEvaluating, checkpointSummary.totalReady, refetch])

  useEffect(() => {
    if (!loading && predictions.length > 0 && !autoEvaluationRan) {
      runAutoEvaluation()
    }
  }, [loading, predictions.length, autoEvaluationRan, runAutoEvaluation])

  const handleBulkEvaluate = async () => {
    setBulkEvaluating(true)
    setEvaluationMessage(null)
    try {
      const response = await fetch('/api/evaluate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ autoEvaluate: true })
      })
      const responseData = await response.json()
      setEvaluationMessage(`Evaluated ${responseData.summary?.evaluated || 0} checkpoints`)
      refetch()
    } catch {
      setEvaluationMessage('Bulk evaluation failed')
    } finally {
      setBulkEvaluating(false)
    }
  }

  if (error) {
    return (
      <div className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-6 text-center">
        <p className="text-rose-400">{error}</p>
      </div>
    )
  }

  if (loading) {
    return (
      <div className="space-y-4">
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
          {Array.from({ length: 4 }).map((_, i) => (
            <Skeleton key={i} className="h-[90px] rounded-xl bg-zinc-800/50" />
          ))}
        </div>
        {Array.from({ length: 3 }).map((_, i) => (
          <Skeleton key={i} className="h-[100px] rounded-xl bg-zinc-800/50" />
        ))}
      </div>
    )
  }

  if (predictions.length === 0) {
    return (
      <div className="rounded-xl border border-zinc-800 bg-zinc-900/50 p-12 text-center">
        <p className="text-zinc-500">No predictions yet</p>
        <p className="text-sm text-zinc-600 mt-1">
          Predictions will appear here as they are generated by the AI agents
        </p>
      </div>
    )
  }

  const hasPendingCheckpoints = checkpointSummary.totalReady > 0

  return (
    <div className="space-y-6">
      <AccuracyMetrics predictions={predictions} />
      
      {(hasPendingCheckpoints || evaluationMessage) && (
        <div className="rounded-xl border border-zinc-800 bg-zinc-900/50 p-4">
          <div className="flex items-center justify-between flex-wrap gap-3">
            <div className="flex items-center gap-4">
              {checkpointSummary.ready5d > 0 && (
                <span className="text-xs px-2 py-1 rounded-full bg-sky-500/10 text-sky-400 border border-sky-500/20">
                  {checkpointSummary.ready5d} @ 5d
                </span>
              )}
              {checkpointSummary.ready10d > 0 && (
                <span className="text-xs px-2 py-1 rounded-full bg-violet-500/10 text-violet-400 border border-violet-500/20">
                  {checkpointSummary.ready10d} @ 10d (Primary)
                </span>
              )}
              {checkpointSummary.ready20d > 0 && (
                <span className="text-xs px-2 py-1 rounded-full bg-amber-500/10 text-amber-400 border border-amber-500/20">
                  {checkpointSummary.ready20d} @ 20d
                </span>
              )}
            </div>
            
            <div className="flex items-center gap-3">
              {evaluationMessage && (
                <span className="text-xs text-emerald-400 flex items-center gap-1">
                  <CheckCircle2 className="h-3.5 w-3.5" />
                  {evaluationMessage}
                </span>
              )}
              
              {hasPendingCheckpoints && (
                <button
                  onClick={handleBulkEvaluate}
                  disabled={bulkEvaluating || autoEvaluating}
                  className={cn(
                    'flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-all',
                    'bg-violet-500/20 text-violet-400 hover:bg-violet-500/30 border border-violet-500/30',
                    (bulkEvaluating || autoEvaluating) && 'opacity-50 cursor-not-allowed'
                  )}
                >
                  {bulkEvaluating || autoEvaluating ? (
                    <Loader2 className="h-3.5 w-3.5 animate-spin" />
                  ) : (
                    <PlayCircle className="h-3.5 w-3.5" />
                  )}
                  Evaluate All Ready
                </button>
              )}
            </div>
          </div>
        </div>
      )}
      
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {predictions.map(prediction => (
          <PredictionCard 
            key={prediction.id} 
            prediction={prediction}
            showTicker={!ticker}
            price={prediction.stock?.ticker ? prices[prediction.stock.ticker] : undefined}
            onEvaluated={refetch}
          />
        ))}
      </div>
    </div>
  )
}